name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push API image
        run: |
          # Build API image
          docker build \
            -t imadch/testtuteur1:api-latest \
            -f ./api/Dockerfile \
            ./api

          # (Optionnel) Tag avec commit SHA pour versionner
          docker tag imadch/testtuteur1:api-latest imadch/testtuteur1:api-${{ github.sha }}

          # Push de l'image "latest" et de la version "sha"
          docker push imadch/testtuteur1:api-latest
          docker push imadch/testtuteur1:api-${{ github.sha }}

  deploy-to-railway:
    runs-on: ubuntu-latest
    needs: build-and-push   # Attendre que le job "build-and-push" soit fini
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
